# Generated by Django 5.0.2 on 2024-04-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
    ]
