# Generated by Django 5.0.2 on 2024-04-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
